"""Item

Revision ID: a778813d7391
Revises: c206f34b7afb
Create Date: 2025-02-12 22:14:13.571169

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from app.db.models import Item

# revision identifiers, used by Alembic.
revision: str = 'a778813d7391'
down_revision: Union[str, None] = 'c206f34b7afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.CheckConstraint('price >= 0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    # ### end Alembic commands ###

    data = (
        ("t-shirt",	80),
        ("cup", 20),
        ("book", 50),
        ("pen",	10),
        ("powerbank", 200),
        ("hoody", 300),
        ("umbrella", 200),
        ("socks", 10),
        ("wallet", 50),
        ("pink-hoody", 500),
    )
    with sa.orm.Session(op.get_bind()) as session:
        items = (Item(type=t, price=p) for t, p in data)
        session.add_all(items)
        session.commit()

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
